### ISSUE TITLE
Suggestions d'améliorations

### ISSUE THREAD

**Issue by hista** [XenoX/AdopteUnMecBOT#1]
Salut,
Bravo pour ton script qui fonctionne très bien et m'a fait réutiliser AUM !
Quelques suggestions d'amélioration que je te soumets : 
- la possibilité de lancer automatiquement les recherches à intervalles régulier (infinite loop)
- la possibilité de lancer des profils de recherches différents, car basés sur des mots-clés différents (search = 'métalleuse de Paris de moins de 50ans' puis search = 'jongleuse de Versailles de moins de 30ans' puis search = 'rentière de Neuilly de plus de 80ans', etc)
- la possibilité de stocker les ID des profils visités, afin de ne pas revisiter 2 fois fois le même profil (avant reset de cet historique)
- réductions des ressources utilisées : est-il possible de lancer le script en headless ?
D'autant que je rencontre souvent des crash de chrome, ce qui est d'ailleurs sans doute plus lié à lui qu'à ton script : 
`selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=74.0.3729.28)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 5.18.0-2-amd64 x86_64)`

Au plaisir de te lire !

**Comment by hista** [comment]
Concernant le dernier point (les crash aléatoires de chrome), coupable trouvé : en désactivant l'accélération matérielle plus de crash (--disable-gpu) !
edit fausse joie : s/plus/moins/

**Comment by XenoX** [comment]
Salut, 
Merci pour tes retours pertinants ! 

Je prends note pour améliorer cette première version "simpliste" :)

N'hésite pas à pull de temps en temps, certaines améliorations devraient arriver vite ;)

**Comment by hista** [comment]
Avec plaisir, d'autant que j'ai entre temps résolu mes crash de chrome sous debian sid, en ajoutant un dépôt plus récent. 

Tu comptes commencer par quelle amélioration ?

**Comment by XenoX** [comment]
Pour la possibilité de lancer les recherches à intervalles régulier, après réflexion, je ne vois pas trop l'utilité. On va beaucoup tomber sur les mêmes profils...
Si vraiment c'est une fonctionnalité qui t'intéresse, tu peux toujours passer par une tâche CRON ou un script bash qui lance le script python à interval régulier.

Pour avoir une liste de plusieurs recherches, c'est mergé, voici le commit : https://github.com/XenoX/AdopteUnMecBOT/commit/f21618ad1bf93882d518d0304cb18292345d25dd

Pour la possibilité de stocker des ID des profils visités, je m'en occupe bientôt, je vais aussi ajouter une "black list" manuelle de profils, si vraiment on ne souhaite pas visiter un ou plusieurs profils en particulier. (edit: https://github.com/XenoX/AdopteUnMecBOT/commit/f6df4dd42ccb9616595e2eb985bc826918343275)

Pour le mode headless, j'ai regardé et apparrement ce n'est pas possible car j'utilise des actions de click, je me re-pencherai plus tard dessus.

**Comment by hista** [comment]
Bonjour,
merci pour le merge, testé et approuvé !
Pour le script bash, tu mettrais quoi dedans pour qu'il relance le script python, mieux qu'à intervalle régulier, lorsque le script python a terminé sa tâche ?
Bonne idée en effet pour la blacklist d'ID, j'aurai quelques profils à mettre dedans ;-)
Enfin pour le headless, c'était surtout pour réduire la consommation CPU et RAM. L'idéal serait de pouvoir faire tourner le script sur un serveur ou raspberrypi. Auparavant j'utilisais le fabuleux weboob devenu woob et son module aum, vu les dépendances requises ça tournait en headless sur une toute petite machine : https://gitlab.com/woob/woob/-/tree/master/modules/aum

**Comment by XenoX** [comment]
Exclude list mergé, voici le commit : https://github.com/XenoX/AdopteUnMecBOT/commit/f6df4dd42ccb9616595e2eb985bc826918343275

**Comment by hista** [comment]
À présent que le script refonctionne, je me repenche sur cette question :

Pour le script bash, tu mettrais quoi dedans pour qu'il relance le script python, mieux qu'à intervalle régulier, lorsque le script python a terminé sa tâche ?

**Comment by XenoX** [comment]
Tu peux créer un ficher script.sh à la racine du projet :
```sh
#!/bin/bash

while [ true ]; do
    python3 main.py
done
```
```sh
$ chmod +x script.sh
```
```sh
$ ./script.sh
```

**Comment by hista** [comment]
Super merci, entre temps j'utilisais un truc bourrin mais qui fonctionne bien : 
while true; do echo ' CTRL+C to stop'; /mon/script ; done

Question bonus : quelle est la syntaxe correcte pour exclure plusieurs profils des visites du bot ?

Le code prévoit :
```
# List of profile(s) link(s) (eg:https://www.adopteunmec.com/profile/1234)
    exclude_profiles_links = []
    #######################################################
```
    
Or si j'ajoute des profils à exclure sous cette forme, le script bloque sur une erreur de syntaxe :

```
# List of profile(s) link(s) (eg:https://www.adopteunmec.com/profile/1234)
    exclude_profiles_links = [https://www.adopteunmec.com/profile/1234]
    #######################################################
```
    
    
Idem pour 

```
# List of profile(s) link(s) (eg:https://www.adopteunmec.com/profile/1234)
    exclude_profiles_links = [
    https://www.adopteunmec.com/profile/1234
    https://www.adopteunmec.com/profile/5678
    ]
    #######################################################
```

Quelle est la bonne manière de procéder ? :)

**Comment by XenoX** [comment]
```python
exclude_profiles_links = [
    'https://www.adopteunmec.com/profile/1234',
    'https://www.adopteunmec.com/profile/5678'
]
```
